GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "user3",
    "email": "user3@email.com",
    "password": "123456"
}


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user3@email.com",
    "password": "123456"
}


###
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InVzZXIzIiwiZW1haWwiOiJ1c2VyM0BlbWFpbC5jb20iLCJyb2xlcyI6WyJVc2VyIl0sImNyZWF0ZWRBdCI6IjIwMjQtMTItMDdUMTQ6NTI6MDcuNzg4WiIsInVwZGF0ZWRBdCI6IjIwMjQtMTItMDdUMTQ6NTI6MDcuNzg4WiIsImlhdCI6MTczMzU5NDIwNCwiZXhwIjoxNzMzNjA0MjA0fQ.9XMlWo9LMtpgnL4puAlOyqriu_dI9dAlnALzCABWP2w

{
    "name": "Partner 1",
    "active": true
}